### ISSUE TITLE
Topic subscription does not work properly, only one message is displayed

### ISSUE THREAD

**Issue by ruffp** [jmstoolbox/jmstoolbox#19]
## Specifications
- JMSToolBox version: V4.10.0 
- OS (Name, version, 32/64bits): Linux CentOS 6.9 64bits
- Q provider (kind, version): ActiveMQ 5.10.2 / OpenWire connection (61616)

## Expected Behavior
When subscribing to a topic, more than one messages should be displayed if the Maximum message is set to more than 1.

When the settings is 0 it should display /catch all messages of the topic.

## Actual Behavior
Despite the setting "Maximum message displayed" is configured to 50, only one message is displayed.
Changing the setting to 200 does have the same effect, setting to '0' (unlimited) does not work at all.

If there is a continuous flow of messages, stopping the subscription and starting again will catch another message (only 1).

## Steps to Reproduce the Problem

  1. Setup OpenWire connection: failover://(tcp://host-1.mydomain.net:61616,tcp://host-2.mydomain.net:61616)
  2. Setup JMX connection (1 = master, 2 = slave): 
	    1: host-1.mydomain.net:1099
	    2: host-2.mydomain.net:1099
  3. Scenario-1 - Subscribe to a Topic, "Max Messages Displayed" = 50 (default value)
  4. Few messages sent to Topic (between ~5)
  5. Only first messages is catched in the UI
  6. Scenario 2 - Change "Max Messages Displayed" = 200 
  7. Stop subsribing to the Topic
  8. Subscribe to the Topic
  9. Few messages sent to Topic (between ~5)
  10. Only first messages is catched in the UI
  11. Scenario-3 - Change "Max Messages Displayed" = 0 (unlimited) 
  12. Stop subsribing to the Topic
  13. Subscribe to the Topic
  14. Few messages sent to Topic (between ~5)
  15. Green Arrow Icon becomes yellow with White Exclamation mark (!) inside, no message displayed.

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

jmstoolbox.log:

2018-07-19 11:49:40:655 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:49:40:681 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:49:46:451 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-2-49314-1531796445858-139:1:2:1:1484'
2018-07-19 11:50:09:031 DEBUG [.c.JTBSessionContentViewPart] Stopping subscription
2018-07-19 11:50:09:031 DEBUG [.c.JTBSessionContentViewPart] Subscription stopped.
2018-07-19 11:50:10:096 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:50:10:115 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:50:16:540 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-1-49310-1531814581012-127:1:2:1:1524'
2018-07-19 11:50:53:042 DEBUG [.c.JTBSessionContentViewPart] Stopping subscription
2018-07-19 11:50:53:043 DEBUG [.c.JTBSessionContentViewPart] Subscription stopped.
2018-07-19 11:50:56:375 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:50:56:391 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:51:07:711 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-2-49314-1531796445858-139:1:2:1:1489'
2018-07-19 11:51:21:307 DEBUG [o.t.j.u.p.JTBMessageViewPart] JTBMessageViewPart refresh for JTBMessage [jtbDestination=MY_TOPIC.Mirrored, jmsMessage ID=ID:HOST-1-49310-1531814581012-127:1:2:1:1524, jtbMessageType=TEXT, replyToDestinationName=MY_TOPIC_RESPONSE, deliveryMode=PERSISTENT, priority=4, timeToLive=null, deliveryDelay=null]
2018-07-19 11:51:21:376 DEBUG [o.t.j.h.MessageViewHandler  ] execute. Message = [JTBMessage [jtbDestination=MY_TOPIC.Mirrored, jmsMessage ID=ID:HOST-1-49310-1531814581012-127:1:2:1:1524, jtbMessageType=TEXT, replyToDestinationName=MY_TOPIC_RESPONSE, deliveryMode=PERSISTENT, priority=4, timeToLive=null, deliveryDelay=null]]

**Comment by titou10titou10** [comment]
Thanks for reporting !

Indeed stopping and starting again a Topic subscription is broken in many ways in v4.10.0:

- Each time the subscription was resumed, a new JMS `MessageListener` was added, causing a mess in the way the messages were held
- The messages limit set with the selector in the view was not correctly handled, due to multiple listeners
- Setting limit to "0" was also not handled correctly.
- Finally, adding a selector with the contextual menu from a message property is causing a `NullPointerException`    

Those are all fixed in coming v4.11.0

**Comment by ruffp** [comment]
Good to see it's fixed already, do you know when the new version will be available?

**Comment by ruffp** [comment]
i just upgraded to 4.11.0 but the issue is still here. Should I create a new bug report or there's a way to re-open this one?

**Comment by titou10titou10** [comment]
As the failing scenarios are not the same (point 15?), yes could you open another issue with the scenario to reproduce the bug?
Also could you upgrade to the latest version (v4.12.1). Even if no code related to the problem has changed, it will be easier for me to debug 
Thanks
Denis
